language: cpp
os: linux
dist: bionic
compiler:
  - gcc
addons:
  snaps:
    - ffsend
  apt:
    update: true
    packages:
      - build-essential
      - cmake
      - pkg-config
      - yasm
      - git
      - gfortran
      - libjpeg8-dev
      - libpng-dev
      - software-properties-common
      - libtiff-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libdc1394-22-dev
      - libxine2-dev
      - libv4l-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgtk2.0-dev
      - libtbb-dev
      - qt5-default
      - libatlas-base-dev
      - libfaac-dev
      - libmp3lame-dev
      - libtheora-dev
      - libvorbis-dev
      - libxvidcore-dev
      - libopencore-amrnb-dev
      - libopencore-amrwb-dev
      - libavresample-dev
      - x264
      - v4l-utils
      - libprotobuf-dev
      - protobuf-compiler
      - libgoogle-glog-dev
      - libgflags-dev
      - libgphoto2-dev
      - libeigen3-dev
      - libhdf5-dev
      - doxygen
script:
  - "./build.sh"
