name: Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-18.04]
        cv-version: [4.1.2, 3.4.8]
    
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v1
    - name: Download depedencies
      run: ./dep.sh
    - name: Build deb
      run: ./build.sh {{ matrix.cv-version }}

